### ISSUE TITLE
Education section overhaul

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.University#235]
- [x] Introduce year of the beginning of training.
- [x] ~~Allow attach edu. program profile documents to multiple edu. program profile forms / recruitment years~~ - moved to separate issue #244 which must be addressed in subsequent releases
- [x] New module to display information about edu. program volume by years #239 
- [x] New module to display information about work programs of practice #239
- [x] ~~Possibly move accreditation dates to the edu. program entity~~ - not needed
- [x] #190
- [x] #247
