### ISSUE TITLE
Export employee data into spreadsheet

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.University#305]
- Based on NPOI library
- Liquid-like template language
- Provide XLSX template with fields and repeatable areas
- Support multi-language templates
- Use Recapcha (or timeout) to avoid leeching for non-authenticated users https://developers.google.com/recaptcha/docs/display
- Allow logged in users to download form w/o captcha
- Export via DNN WebAPI

## Compare spreadsheets:

- Additional action for editors to download form in text mode (e.g. CSV and/or YAML)
- Separate admin module to convert XSLX form into text (upload XLSX, download text).
- Use command-line diff script or desktop app (e.g. Meld, Winmerge) or online service to compare text files to detect changes.

## TODO:

- [x] TemplateEngine, ModelBinder
- [x] User UI
- [x] Export to CSV(-like)
- [x] Admin UI: WorkbookConverter module
- [x] Don't use reCaptcha for logged in users
- [x] Disable export functionality for general users completely (hide the button) if reCaptcha not configured (no/empty site key).

**Comment by roman-yagodin** [comment]
Issues detected after first deploy:
- [ ] Don't use reCaptcha for logged in users
- [ ] Switch off export for general users if reCaptcha not configured (no site key)
